### ISSUE TITLE
I get an error when trying to build.

### ISSUE THREAD

**Issue by elorest** [drujensen/blog-kemalyst#1] opened 2016-05-18 06:32 UTC
Error in ./src/models/post.cr:6: class variable '@@database' of Post must be Kemalyst::Adapter::Pg, not Nil

I have postgres on my computer and I followed the instructions in the readme. Is there somewhere else I need to configure?

**Comment by drujensen** [comment] 2016-05-18 13:38
@isaacsloan I should probably have better error handling here.  This is saying it couldn't connect to your database.  Check your database.yml and make sure the settings are correct.  You might need to create the database in postgres as well.

**Comment by isaacsloan** [comment] 2016-05-18 15:10
Thanks. I wasn't sure on the syntax for blank password. If I wanted you use
mysql instead shat drivers would I need?

**Comment by drujensen** [comment] 2016-05-18 16:25
waterlink/crystal-mysql is the mysql driver.  I have had issues with the latest version of the driver and haven't had time to track it down so your milage may vary.

To send a blank password, you would remove it from between the : and the @ sign like so:
`postgres://root:@localhost:5432/blog`

**Comment by isaacsloan** [comment] 2016-05-18 21:41
Thanks... Weirdly I get that error no matter what I tried. I can access the database just fine from a rails app. I even tried configuring it like this with no luck.

````yaml
pg:
  host: 127.0.0.1
  port: 5432
  database: blog
  username: isaac
  password:

````

I wonder if perhaps I need to be using an older version of crystal.

**Comment by drujensen** [comment] 2016-05-18 22:04
I verified that its failing with 0.16.0.  It works with 0.15.0. Thanks for letting me know.  I will look into fixing it soon.

**Comment by isaacsloan** [comment] 2016-05-19 20:24
Thanks.

**Comment by drujensen** [comment] 2016-05-20 18:47
@isaacsloan I updated kemalyst to support 0.17.0.  There were some fairly big breaking changes in 0.16.0 related to typing and instance variables.  This change forces you to specify the types of member variables in your classes, which is not very DRY.  For now, I added the type to the `sql_mapping` but I'm not happy with it.  I will look at a way to refactor this.

**Comment by isaacsloan** [comment] 2016-05-24 18:18
Thanks. I don't know why I'm having such a hard time getting this to compile. I'm running crystal 0.17.2, adding this to my database.yml `database: "postgres://isaac:@127.0.0.1:5432/blog"`, and running crystal build src/app.cr.

**Comment by drujensen** [comment] 2016-05-24 18:40
What error message are you getting?

**Comment by isaacsloan** [comment] 2016-05-24 19:36
Error in ./src/app.cr:4: instantiating 'Kemalyst::Application#start()'

Kemalyst::Application.instance.start
                               ^~~~~

in ./libs/kemalyst/kemalyst.cr:69: instantiating 'HTTP::Server#listen()'

      server.listen
             ^~~~~~

in macro 'spawn' /Users/isaac/.crenv/versions/0.17.2/src/concurrent/concurrent.cr:94, line 9:

  1.   
  2.     ->(
  3.       
  4.         __arg0 : typeof(server.accept),
  5.       
  6.       
  7.       ) {
  8.       spawn do
  9.         handle_client(
 10.           
 11.             __arg0,
 12.           
 13.           
 14.         )
 15.       end
 16.     
 17.       }.call(server.accept)
 18.     
 19.   

        handle_client(
        ^~~~~~~~~~~~~

instantiating 'handle_client(TCPSocket+)'
in /Users/isaac/.crenv/versions/0.17.2/src/http/server/server.cr:180: instantiating '((HTTP::Server::Context -> Void) | HTTP::Handler+)#call(HTTP::Server::Context)'

        @handler.call(context)
                 ^~~~

in ./libs/kemalyst/kemalyst/handler/websocket.cr:71: instantiating 'call_next(HTTP::Server::Context)'

        call_next(context)
        ^~~~~~~~~

in /Users/isaac/.crenv/versions/0.17.2/src/http/server/handler.cr:22: instantiating '((HTTP::Server::Context -> Void) | HTTP::Handler+)#call(HTTP::Server::Context)'

      next_handler.call(context)
                   ^~~~

in ./libs/kemalyst/kemalyst/handler/static.cr:16: instantiating 'call_next(HTTP::Server::Context)'

        call_next(context)
        ^~~~~~~~~

in /Users/isaac/.crenv/versions/0.17.2/src/http/server/handler.cr:22: instantiating '((HTTP::Server::Context -> Void) | HTTP::Handler+)#call(HTTP::Server::Context)'

      next_handler.call(context)
                   ^~~~

in ./libs/kemalyst/kemalyst/handler/session.cr:21: instantiating 'call_next(HTTP::Server::Context)'

      call_next(context)
      ^~~~~~~~~

in /Users/isaac/.crenv/versions/0.17.2/src/http/server/handler.cr:22: instantiating '((HTTP::Server::Context -> Void) | HTTP::Handler+)#call(HTTP::Server::Context)'

      next_handler.call(context)
                   ^~~~

in ./libs/kemalyst/kemalyst/handler/router.cr:99: instantiating 'process_request(HTTP::Server::Context)'

      process_request(context)
      ^~~~~~~~~~~~~~~

in ./libs/kemalyst/kemalyst/handler/router.cr:143: instantiating 'HTTP::Handler+#call(HTTP::Server::Context)'

            if content = route.handler.call(context) as String
                                       ^~~~

in ./libs/kemalyst/kemalyst/handler/params.cr:17: instantiating 'call_next(HTTP::Server::Context)'

      call_next(context)
      ^~~~~~~~~

in /Users/isaac/.crenv/versions/0.17.2/src/http/server/handler.cr:22: instantiating '((HTTP::Server::Context -> Void) | HTTP::Handler+)#call(HTTP::Server::Context)'

      next_handler.call(context)
                   ^~~~

in ./libs/kemalyst/kemalyst/handler/logger.cr:17: instantiating 'call_next(HTTP::Server::Context)'

      call_next(context)
      ^~~~~~~~~

in /Users/isaac/.crenv/versions/0.17.2/src/http/server/handler.cr:22: instantiating '((HTTP::Server::Context -> Void) | HTTP::Handler+)#call(HTTP::Server::Context)'

      next_handler.call(context)
                   ^~~~

in ./libs/kemalyst/kemalyst/handler/error.cr:9: instantiating 'call_next(HTTP::Server::Context)'

        call_next(context)
        ^~~~~~~~~

in /Users/isaac/.crenv/versions/0.17.2/src/http/server/handler.cr:22: instantiating '((HTTP::Server::Context -> Void) | HTTP::Handler+)#call(HTTP::Server::Context)'

      next_handler.call(context)
                   ^~~~

in ./libs/kemalyst/kemalyst/handler/cors.cr:35: instantiating 'call_next(HTTP::Server::Context)'

          call_next(context)
          ^~~~~~~~~

in /Users/isaac/.crenv/versions/0.17.2/src/http/server/handler.cr:22: instantiating '((HTTP::Server::Context -> Void) | HTTP::Handler+)#call(HTTP::Server::Context)'

      next_handler.call(context)
                   ^~~~

in ./libs/kemalyst/kemalyst/handler/basicauth.cr:27: instantiating 'call_next(HTTP::Server::Context)'

            return call_next(context) if authorized?(value)
                   ^~~~~~~~~

in /Users/isaac/.crenv/versions/0.17.2/src/http/server/handler.cr:22: instantiating '((HTTP::Server::Context -> Void) | HTTP::Handler+)#call(HTTP::Server::Context)'

      next_handler.call(context)
                   ^~~~

in ./libs/kemalyst/kemalyst/handler/base.cr:33: instantiating 'call_next(HTTP::Server::Context)'

      call_next context
      ^~~~~~~~~

in /Users/isaac/.crenv/versions/0.17.2/src/http/server/handler.cr:22: instantiating '((HTTP::Server::Context -> Void) | HTTP::Handler+)#call(HTTP::Server::Context)'

      next_handler.call(context)
                   ^~~~

in ./src/controllers/post_controller.cr:75: no overload matches 'Post#name=' with type (Array(JSON::Type) | Bool | Float64 | Hash(String, JSON::Type) | Int64 | String | Nil)
Overloads are:
 - Post#name=(name : String | ::Nil)
Couldn't find overloads for these types:
 - Post#name=(name : Array(JSON::Type))
 - Post#name=(name : Bool)
 - Post#name=(name : Float64)
 - Post#name=(name : Hash(String, JSON::Type))
 - Post#name=(name : Int64)

          post.name = context.params["name"]
               ^~~~

================================================================================

Nil trace:

  /Users/isaac/.crenv/versions/0.17.2/src/hash.cr:56

      def [](key)
          ^~

  /Users/isaac/.crenv/versions/0.17.2/src/hash.cr:57

        fetch(key)
        ^~~~~

  /Users/isaac/.crenv/versions/0.17.2/src/hash.cr:102

      def fetch(key)
          ^~~~~

  /Users/isaac/.crenv/versions/0.17.2/src/hash.cr:103

        fetch(key) do
        ^~~~~

  /Users/isaac/.crenv/versions/0.17.2/src/hash.cr:131

      def fetch(key)
          ^~~~~

  /Users/isaac/.crenv/versions/0.17.2/src/hash.cr:133

        entry ? entry.value : yield key
        ^

  /Users/isaac/.crenv/versions/0.17.2/src/hash.cr:133

        entry ? entry.value : yield key
                      ^~~~~

  macro getter (in /Users/isaac/.crenv/versions/0.17.2/src/object.cr:218):7

          def value
              ^~~~~

  macro getter (in /Users/isaac/.crenv/versions/0.17.2/src/object.cr:218):8

            @value
            ^~~~~~

  macro setter (in /Users/isaac/.crenv/versions/0.17.2/src/object.cr:411):4

            def value=(@value : V)
                       ^~~~~

  macro setter (in /Users/isaac/.crenv/versions/0.17.2/src/object.cr:411):4

            def value=(@value : V)

**Comment by drujensen** [comment] 2016-05-24 22:25
can you confirm the /src/models/post.cr has this mapping?:

```
class Post < Kemalyst::Model
  adapter pg
 
  sql_mapping({ 
    name: ["VARCHAR(255)", String] 
    body: ["TEXT", String]
  })
...
```

**Comment by drujensen** [comment] 2016-05-24 22:27
Also, please confirm that you performed a `shards update` to get the latest `kemalyst`.

**Comment by isaacsloan** [comment] 2016-05-24 23:40
Confirmed.

**Comment by isaacsloan** [comment] 2016-05-25 00:13
````ruby
require "kemalyst"
require "kemalyst/adapter/pg"
require "markdown/markdown"

class Post < Kemalyst::Model
  adapter pg
  
  sql_mapping({ 
    name: ["VARCHAR(255)", String] 
    body: ["TEXT", String]
  })

  def last_updated
    last_updated = updated_at
    if last_updated.is_a?(String)
      last_updated = Time::Format.new("%F %X").parse(last_updated)
    end
    if last_updated.is_a?(Time)
      formatter = Time::Format.new("%B %d, %Y")
      last_updated = formatter.format(last_updated)
    end
    return last_updated
  end

  def markdown_body
    markdown_body = body
    if markdown_body.is_a?(String)
      markdown_body = Markdown.to_html(markdown_body)
    end
    return markdown_body
  end
end
````

**Comment by drujensen** [comment] 2016-05-25 01:27
I think I found the issue.  Pull down the latest master and try again.

In the controller, I didn’t specify the type when assigning to the model object.  This used to work before 0.16.0.

```
post.name = context.params["name"] as String
```

I added the `as String` to cast to the appropriate type.  Let me know if that fixed it.

**Comment by isaacsloan** [comment] 2016-05-25 03:26
````
Error in ./src/app.cr:2: while requiring "../config/*"

require "../config/*"
^

in ./config/routes.cr:1: while requiring "../src/controllers/*"

require "../src/controllers/*"
^

in ./src/controllers/post_controller.cr:1: while requiring "../models/post"

require "../models/post"
^

Syntax error in ./src/models/post.cr:10: expecting token '}', not 'body'

    body: ["TEXT", String]
    ^
````

**Comment by isaacsloan** [comment] 2016-05-25 03:27
Am I supposed to create the tables manually or are there migrations?

**Comment by drujensen** [comment] 2016-05-25 14:48
Ok.  super strange.  The model compiles for me but there is definitely a syntax error here. There should be a comma after `name: ["VARCHAR(255)", String]`. I pushed a fix.

**Comment by drujensen** [comment] 2016-05-25 14:51
There is a simple migration script but it drops and creates the table so be aware that you will lose your data if you don’t back it up first.

`db/migrate.cr`
```
require "../src/models/*"

Post.drop
Post.create
```

**Comment by drujensen** [comment] 2016-05-25 16:06
I cannot duplicate this issue.  It looks like the for loop in a macro will still work without a comma in the hash. 

https://play.crystal-lang.org/#/r/zn0 <https://play.crystal-lang.org/#/r/zn0>

Can you provide more information?  What OS and Crystal version are you compiling with?

**Comment by isaacsloan** [comment] 2016-05-25 16:22
OSX 10.11, Crystals 0.17.2.

**Comment by drujensen** [comment] 2016-05-25 16:41
Are you still seeing the same issue with the latest changes?

**Comment by isaacsloan** [comment] 2016-05-25 18:06
So weird. I updated the blog code, shards update, but still get this error. Thanks for all the help.
````
Syntax error in ./libs/pg/pg/decoder.cr:103: unterminated call

        (pointerof(u32).as(Float32*)).value
                          ^
````

**Comment by drujensen** [comment] 2016-05-25 18:16
Strange, syntax error in the pg driver? What version of postgres do you have?

```
$postgres --version
postgres (PostgreSQL) 9.5.1
```

**Comment by isaacsloan** [comment] 2016-05-25 18:23
PostgreSQL 9.5.2

**Comment by drujensen** [comment] 2016-05-31 17:20
@isaacsloan I cannot duplicate the issue but it looks like the latest postgres driver requires a password in the DATABASE_URL.  Can you set a username/password in postgres, give permission to the database `blog` and see if that addresses your issue?

`postgres://username:password@localhost:5432/blog`

**Comment by drujensen** [comment] 2016-11-04 04:27
updated kemalyst model to use the new db drivers.  This should address your issue.

**Closed by drujensen** 2016-11-04 04:27 UTC
